engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    # config:
    #   languages:
    #   - ruby
    #   - javascript
    #   - python
    #   - php
  eslint:
    enabled: false
  fixme:
    enabled: false
  phpmd:
    enabled: false
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- "bootstrap/cache"
- "resources/"
- "storage/"
- "tests/"
- "**.md"
- "**.min.js"
- "**.min.php"
- "**.min.css"
